import type { Stakeholder } from "../api/discover/route";

const RENEWABLE_ENERGY_LEBANON: Stakeholder[] = [
  {
    name: "Minister of Energy and Water, Republic of Lebanon",
    organization: "Ministry of Energy and Water (MoEW)",
    current_officeholder: "To be verified",
    type: "government",
    category: "Government & Regulatory",
    influence_score: 9,
    stance: "neutral",
    key_positions: [
      "Controls national grid policy and renewable energy licensing framework, with authority over all utility-scale project approvals",
      "Has signalled conditional support for solar subsidies but is constrained by IMF fiscal consolidation requirements and EDL debt",
      "Oversees Ã‰lectricitÃ© du Liban restructuring plan, which is a prerequisite for bankable grid-connection agreements",
    ],
    engagement_recommendation:
      "Request a ministerial-level briefing to align project milestones with MoEW's 2026 sector reform roadmap; frame the project as supporting EDL transition, not bypassing it.",
    contact: "https://energyandwater.gov.lb",
    coordinates: [35.50, 33.89],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Director General, Lebanese Center for Energy Conservation (LCEC)",
    organization: "Lebanese Center for Energy Conservation (LCEC)",
    current_officeholder: "To be verified",
    type: "government",
    category: "Government & Regulatory",
    influence_score: 7,
    stance: "supportive",
    key_positions: [
      "Implements Lebanon's UNDP-backed net-metering programme for rooftop solar, covering over 6,000 registered installations",
      "Authored Lebanon's National Renewable Energy Action Plan (NREAP) targeting 30% renewables by 2030",
      "Coordinates EU-funded capacity building for municipal energy managers across 30+ Lebanese municipalities",
    ],
    engagement_recommendation:
      "Co-develop technical annexes and feasibility documentation with LCEC to leverage their regulatory credibility with international donors and the World Bank.",
    contact: "https://lcec.org.lb",
    coordinates: [35.51, 33.88],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Electricity Regulatory Authority (ERA)",
    organization: "Electricity Regulatory Authority of Lebanon",
    current_officeholder: "To be verified",
    type: "government",
    category: "Government & Regulatory",
    influence_score: 7,
    stance: "neutral",
    key_positions: [
      "Newly established regulator with authority over tariff-setting and licensing for private power generation",
      "Mandated under Law 462 to create a competitive electricity market, but operational capacity remains limited",
      "Key gatekeeper for independent power producer (IPP) licensing and grid access agreements",
    ],
    engagement_recommendation:
      "Engage early to understand ERA's evolving licensing requirements and position the project as a model for compliant private power generation under the new regulatory framework.",
    contact: "https://era.gov.lb",
    coordinates: [35.49, 33.90],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Municipality of Zahle â€” Mayor's Office",
    organization: "Municipality of Zahle",
    current_officeholder: "To be verified",
    type: "government",
    category: "Government & Regulatory",
    influence_score: 5,
    stance: "supportive",
    key_positions: [
      "Zahle is Lebanon's largest Bekaa Valley city with high solar irradiance and municipal land suitable for solar farms",
      "Has expressed interest in municipal energy self-sufficiency following chronic EDL blackouts",
      "Controls local permitting and zoning for energy infrastructure in the Bekaa region",
    ],
    engagement_recommendation:
      "Propose a municipal solar pilot programme with Zahle as the flagship site to demonstrate local government partnership and build a replicable model for other municipalities.",
    contact: "https://zahle.gov.lb",
    coordinates: [35.90, 33.85],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Layla Saab",
    organization: "Natural Resource Governance Institute (NRGI) â€” MENA",
    current_officeholder: "Layla Saab",
    type: "ngo",
    category: "Civil Society & NGOs",
    influence_score: 6,
    stance: "opposed",
    key_positions: [
      "Publicly critiques opaque procurement processes in energy concessions, with published reports on Lebanon's offshore gas licensing",
      "Advocates for mandatory community benefit-sharing clauses in all renewable energy project agreements",
      "Has flagged governance gaps in Lebanon's energy sector that she argues make large-scale private investment premature",
    ],
    engagement_recommendation:
      "Engage proactively before project launch with full transparency commitments, a published stakeholder consultation log, and a community impact framework to pre-empt public criticism.",
    contact: "https://resourcegovernance.org",
    coordinates: [35.50, 33.89],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Lebanese Environment Forum (LEF)",
    organization: "Lebanese Environment Forum",
    current_officeholder: "To be verified",
    type: "ngo",
    category: "Civil Society & NGOs",
    influence_score: 5,
    stance: "supportive",
    key_positions: [
      "Coalition of 50+ environmental NGOs advocating for renewable energy transition and sustainable development in Lebanon",
      "Has campaigned for community ownership models in renewable energy projects to ensure equitable benefit-sharing",
      "Monitors environmental impact assessments and advocates for stringent ecological safeguards in energy infrastructure",
    ],
    engagement_recommendation:
      "Invite LEF to participate in the project's environmental review process and co-design community engagement protocols to build grassroots legitimacy.",
    contact: "https://lef-lebanon.org",
    coordinates: [35.52, 33.89],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Green Mind Association",
    organization: "Green Mind Association",
    current_officeholder: "To be verified",
    type: "ngo",
    category: "Civil Society & NGOs",
    influence_score: 4,
    stance: "supportive",
    key_positions: [
      "Conducts community-level environmental education and renewable energy awareness campaigns across rural Lebanon",
      "Operates solar-powered community centres in underserved areas, demonstrating grassroots demand for clean energy",
      "Partners with UNDP on community-based adaptation projects with energy components",
    ],
    engagement_recommendation:
      "Partner with Green Mind for community outreach and awareness campaigns to build local acceptance and demonstrate grassroots support for the project.",
    contact: "https://www.greenmind-lb.com",
    coordinates: [35.48, 33.91],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Georges Riachi",
    organization: "Federation of Lebanese Chambers of Commerce, Industry & Agriculture",
    current_officeholder: "Georges Riachi",
    type: "private",
    category: "Private Sector",
    influence_score: 8,
    stance: "supportive",
    key_positions: [
      "Champions private-sector-led energy solutions as the primary mechanism to break the state monopoly strangling Lebanese businesses",
      "Represents generator industry interests transitioning toward solar hybrid systems, creating commercial alignment with project objectives",
      "Has publicly endorsed the World Bank's Emergency Social and Economic Support project energy reform package",
    ],
    engagement_recommendation:
      "Frame engagement around business competitiveness, FDI attraction, and energy cost reduction to secure a private-sector coalition that can lobby MoEW alongside the project team.",
    contact: "https://ccib.org.lb",
    coordinates: [35.50, 33.90],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Marc Toufic",
    organization: "Terrain Solar (Private Developer)",
    current_officeholder: "Marc Toufic",
    type: "private",
    category: "Private Sector",
    influence_score: 6,
    stance: "supportive",
    key_positions: [
      "Operates a 15MW portfolio of commercial and industrial solar installations across Mount Lebanon and the Bekaa",
      "Facing critical grid-connection bottlenecks due to EDL technical incapacity, creating shared advocacy interests",
      "Actively lobbying MoEW and parliament for wheeling rights reform that would allow private power purchase agreements",
    ],
    engagement_recommendation:
      "Include in the project's technical advisory structure to leverage operational ground-truth knowledge and existing municipal permitting relationships across key governorates.",
    contact: "https://terrainsolar.com",
    coordinates: [35.53, 33.88],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Lebanese Solar Energy Society (LSES)",
    organization: "Lebanese Solar Energy Society",
    current_officeholder: "To be verified",
    type: "private",
    category: "Private Sector",
    influence_score: 5,
    stance: "supportive",
    key_positions: [
      "Industry association representing solar installers and distributors with practical knowledge of market barriers",
      "Advocates for standardisation of solar equipment imports and quality certification frameworks",
      "Tracks solar installation data and market pricing, providing ground-truth market intelligence",
    ],
    engagement_recommendation:
      "Engage LSES for market intelligence on local supply chain capacity and to identify qualified local installation partners for project implementation.",
    contact: "https://lses-lb.org",
    coordinates: [35.47, 33.89],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Nour Khalil",
    organization: "L'Orient Today â€” Environment & Energy Desk",
    current_officeholder: "Nour Khalil",
    type: "media",
    category: "Media & Communications",
    influence_score: 5,
    stance: "neutral",
    key_positions: [
      "Covers Lebanon's generator sector and energy subsidy reform with a critical lens, reaching 200,000+ English-language readers",
      "Has published investigative pieces on delays and cost overruns in World Bank-funded EDL rehabilitation contracts",
      "Actively seeks access to technical project documentation and financial models for fact-based reporting",
    ],
    engagement_recommendation:
      "Offer structured quarterly press briefings and access to non-proprietary project data to shape accurate coverage and build a working relationship before any adverse reporting emerges.",
    contact: "https://today.lorientlejour.com",
    coordinates: [35.51, 33.91],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Megaphone News",
    organization: "Megaphone News",
    current_officeholder: "To be verified",
    type: "media",
    category: "Media & Communications",
    influence_score: 5,
    stance: "opposed",
    key_positions: [
      "Independent digital media outlet with strong youth following, known for critical coverage of governance failures in infrastructure",
      "Has produced viral investigative content on electricity sector corruption and generator mafia networks",
      "Amplifies civil society voices and can rapidly shift public opinion on energy projects through social media reach",
    ],
    engagement_recommendation:
      "Monitor Megaphone's coverage actively and prepare proactive transparency materials; consider offering behind-the-scenes access to demonstrate project integrity before critical reporting emerges.",
    contact: "https://megaphone.news",
    coordinates: [35.49, 33.91],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Al-Akhbar â€” Economics Desk",
    organization: "Al-Akhbar Newspaper",
    current_officeholder: "To be verified",
    type: "media",
    category: "Media & Communications",
    influence_score: 4,
    stance: "neutral",
    key_positions: [
      "Arabic-language daily with broad readership covering energy policy from a political economy perspective",
      "Has influence on how energy sector reforms are perceived by the broader Arabic-speaking public in Lebanon",
      "Tracks parliamentary debates on energy legislation and regulatory changes",
    ],
    engagement_recommendation:
      "Develop Arabic-language communications materials and offer interviews to Al-Akhbar's economics desk to ensure balanced coverage reaching the Arabic-speaking audience.",
    contact: "https://al-akhbar.com",
    coordinates: [35.50, 33.88],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Dr. Riad Chedid",
    organization: "American University of Beirut â€” Faculty of Engineering & Architecture",
    current_officeholder: "Dr. Riad Chedid",
    type: "academic",
    category: "Academic & Research",
    influence_score: 6,
    stance: "supportive",
    key_positions: [
      "Published peer-reviewed modelling demonstrating Lebanon's technical potential for 30% renewable penetration by 2030 under reformed grid conditions",
      "Serves as technical advisor to LCEC on grid integration studies and to the UN-Habitat urban energy resilience panel",
      "Co-authors WHO and UNDP reports on the health and economic co-benefits of renewable energy adoption in post-conflict contexts",
    ],
    engagement_recommendation:
      "Commission a third-party technical validation study through AUB to build credibility with the donor community, international lenders, and Lebanese regulatory bodies simultaneously.",
    contact: "https://www.aub.edu.lb/msfea",
    coordinates: [35.48, 33.90],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Issam Fares Institute for Public Policy (IFI)",
    organization: "Issam Fares Institute â€” American University of Beirut",
    current_officeholder: "To be verified",
    type: "academic",
    category: "Academic & Research",
    influence_score: 5,
    stance: "neutral",
    key_positions: [
      "Publishes influential policy briefs on energy governance and climate adaptation in Lebanon and the MENA region",
      "Convenes policy dialogues bringing together government, donors, and civil society on energy transition",
      "Maintains research partnerships with international think tanks providing access to comparative analysis",
    ],
    engagement_recommendation:
      "Commission IFI to produce an independent policy brief evaluating the project's alignment with Lebanon's energy transition goals to build academic credibility.",
    contact: "https://www.aub.edu.lb/ifi",
    coordinates: [35.48, 33.90],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Lebanese University â€” Faculty of Engineering",
    organization: "Lebanese University",
    current_officeholder: "To be verified",
    type: "academic",
    category: "Academic & Research",
    influence_score: 4,
    stance: "supportive",
    key_positions: [
      "Largest public university in Lebanon with engineering graduates who form the bulk of the local technical workforce",
      "Conducts applied research on solar technology adapted to Lebanese climate and grid conditions",
      "Can provide local technical talent pipeline for project implementation and long-term maintenance",
    ],
    engagement_recommendation:
      "Partner with LU's engineering faculty on a workforce development programme to build local technical capacity and demonstrate commitment to knowledge transfer.",
    contact: "https://ul.edu.lb",
    coordinates: [35.53, 33.87],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Head of Infrastructure & Energy Unit, EU Delegation to Lebanon",
    organization: "EU Delegation to Lebanon â€” Infrastructure & Energy Unit",
    current_officeholder: "To be verified",
    type: "international",
    category: "International Organizations & Donors",
    influence_score: 8,
    stance: "supportive",
    key_positions: [
      "Manages a â‚¬200M EU energy envelope for Lebanon, including grid rehabilitation and renewable energy integration grants",
      "Conditions EU funding on regulatory transparency, anti-corruption compliance, and procurement aligned with EU standards",
      "Coordinates with EBRD on grid modernisation co-financing and is actively seeking bankable project pipelines",
    ],
    engagement_recommendation:
      "Present the project as aligned with EU Green Deal neighbourhood objectives and request a co-financing structured dialogue; prepare an EU-standard environmental and social impact assessment in advance.",
    contact: "https://www.eeas.europa.eu/delegations/lebanon",
    coordinates: [35.48, 33.89],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "UNDP Lebanon â€” Energy & Environment Programme",
    organization: "United Nations Development Programme â€” Lebanon",
    current_officeholder: "To be verified",
    type: "international",
    category: "International Organizations & Donors",
    influence_score: 7,
    stance: "supportive",
    key_positions: [
      "Implements the CEDRO programme, Lebanon's flagship renewable energy and energy efficiency initiative",
      "Provides technical assistance to MoEW and LCEC on energy policy and regulatory framework development",
      "Coordinates donor funding for distributed renewable energy systems in underserved communities",
    ],
    engagement_recommendation:
      "Align project design with UNDP's CEDRO framework to access technical assistance and donor coordination mechanisms already established in Lebanon's energy sector.",
    contact: "https://www.undp.org/lebanon",
    coordinates: [35.52, 33.88],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "World Bank â€” Lebanon Energy Programme",
    organization: "World Bank Group â€” Lebanon Country Office",
    current_officeholder: "To be verified",
    type: "international",
    category: "International Organizations & Donors",
    influence_score: 8,
    stance: "neutral",
    key_positions: [
      "Manages the $300M+ Emergency Social and Economic Support programme with energy reform conditionalities",
      "Requires structural reforms in EDL governance as a precondition for continued energy sector lending",
      "Has influence over broader donor community positioning on Lebanon's energy transition pathway",
    ],
    engagement_recommendation:
      "Position the project as supporting World Bank reform conditionalities and seek alignment with the Bank's energy sector lending strategy to access complementary financing.",
    contact: "https://www.worldbank.org/en/country/lebanon",
    coordinates: [35.51, 33.90],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Agence FranÃ§aise de DÃ©veloppement (AFD) â€” Lebanon",
    organization: "Agence FranÃ§aise de DÃ©veloppement",
    current_officeholder: "To be verified",
    type: "international",
    category: "International Organizations & Donors",
    influence_score: 6,
    stance: "supportive",
    key_positions: [
      "Active bilateral donor in Lebanon's energy sector with focus on renewable energy and energy efficiency projects",
      "Provides concessional financing and technical assistance for sustainable infrastructure",
      "Strong relationship with Lebanese government institutions and complementary to EU and World Bank programming",
    ],
    engagement_recommendation:
      "Explore AFD concessional financing instruments for the project and propose alignment with their Lebanon country strategy for energy transition.",
    contact: "https://www.afd.fr/en/page-region-pays/lebanon",
    coordinates: [35.49, 33.88],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
];

const PUBLIC_HEALTH_LEBANON: Stakeholder[] = [
  {
    name: "Minister of Public Health, Republic of Lebanon",
    organization: "Ministry of Public Health (MoPH)",
    current_officeholder: "To be verified",
    type: "government",
    category: "Government & Regulatory",
    influence_score: 9,
    stance: "supportive",
    key_positions: [
      "Leads national hospital accreditation reform and pharmaceutical regulation modernisation following the 2019 financial collapse",
      "Has prioritised the rehabilitation of the primary healthcare network, which lost over 40% of its staff to emigration since 2019",
      "Coordinates with WHO and UNICEF on communicable disease surveillance and the National Immunisation Programme recovery plan",
    ],
    engagement_recommendation:
      "Propose embedding a joint technical working group within MoPH to align deliverables with the National Health Strategy 2021â€“2025 and secure ministerial co-ownership of project outcomes.",
    contact: "https://www.moph.gov.lb",
    coordinates: [35.50, 33.89],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Director General, Order of Pharmacists of Lebanon",
    organization: "Order of Pharmacists of Lebanon",
    current_officeholder: "To be verified",
    type: "government",
    category: "Government & Regulatory",
    influence_score: 6,
    stance: "neutral",
    key_positions: [
      "Regulates pharmaceutical practice and drug distribution, with authority over pharmacy licensing and drug quality standards",
      "Key stakeholder in pharmaceutical supply chain reform and pricing policy following the financial crisis",
      "Tracks medication shortages and counterfeit drug risks that affect project pharmaceutical components",
    ],
    engagement_recommendation:
      "Engage the Order on pharmaceutical quality assurance components of the project to ensure regulatory compliance and leverage their nationwide pharmacy network for distribution.",
    contact: "https://www.opl.org.lb",
    coordinates: [35.51, 33.88],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Qaimmaqam of Akkar District",
    organization: "Akkar District Administration",
    current_officeholder: "To be verified",
    type: "government",
    category: "Government & Regulatory",
    influence_score: 4,
    stance: "supportive",
    key_positions: [
      "Akkar is Lebanon's most underserved district with the highest poverty rates and weakest health infrastructure",
      "Local government authority over health facility permits and coordination with national ministries for district-level implementation",
      "Community health needs in Akkar are acute, creating strong local demand for health intervention projects",
    ],
    engagement_recommendation:
      "Propose Akkar as a priority implementation district to demonstrate impact in underserved areas and build support from local authorities who urgently need health infrastructure investment.",
    contact: "https://akkar.gov.lb",
    coordinates: [36.15, 34.55],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Dr. Alexandra Hamdan",
    organization: "World Health Organization â€” Lebanon Country Office",
    current_officeholder: "Dr. Alexandra Hamdan",
    type: "international",
    category: "International Organizations & Donors",
    influence_score: 8,
    stance: "supportive",
    key_positions: [
      "Manages a $45M WHO emergency health response portfolio across 26 primary healthcare centres and 6 district hospitals",
      "Leads donor harmonisation across 12 UN health-sector partners through the Health Cluster coordination mechanism",
      "Advocates for transitioning Lebanon from emergency humanitarian health response toward a resilient, publicly financed system",
    ],
    engagement_recommendation:
      "Position the project within the Health Cluster framework from day one to access coordinated funding streams, avoid duplication with existing WHO programming, and benefit from WHO's MoPH relationship.",
    contact: "https://www.emro.who.int/countries/lebanon",
    coordinates: [35.52, 33.90],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "UNICEF Lebanon â€” Health & Nutrition Programme",
    organization: "UNICEF â€” Lebanon Country Office",
    current_officeholder: "To be verified",
    type: "international",
    category: "International Organizations & Donors",
    influence_score: 7,
    stance: "supportive",
    key_positions: [
      "Leads child and maternal health programming including immunisation campaigns and nutrition interventions",
      "Operates a nationwide cold chain network critical for vaccine distribution and pharmaceutical logistics",
      "Coordinates with MoPH on school health programmes and adolescent health services",
    ],
    engagement_recommendation:
      "Align maternal and child health components with UNICEF's existing programmes to avoid duplication and leverage their established cold chain and community health worker networks.",
    contact: "https://www.unicef.org/lebanon",
    coordinates: [35.49, 33.90],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "USAID Lebanon â€” Health Office",
    organization: "United States Agency for International Development â€” Lebanon",
    current_officeholder: "To be verified",
    type: "international",
    category: "International Organizations & Donors",
    influence_score: 7,
    stance: "neutral",
    key_positions: [
      "Major bilateral health donor funding primary healthcare strengthening, health workforce development, and pharmaceutical supply chain reform",
      "Conditions funding on governance reforms and accountability measures that shape project design requirements",
      "Has shifted focus toward health system resilience and sustainability, moving away from emergency response modalities",
    ],
    engagement_recommendation:
      "Design project components to align with USAID's health system strengthening priorities and explore co-financing opportunities through their existing Lebanon health portfolio.",
    contact: "https://www.usaid.gov/lebanon",
    coordinates: [35.53, 33.89],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Dr. Ramzi Haddad",
    organization: "Lebanese Medical Association (LMA)",
    current_officeholder: "Dr. Ramzi Haddad",
    type: "academic",
    category: "Academic & Research",
    influence_score: 7,
    stance: "neutral",
    key_positions: [
      "Represents over 5,000 licensed physicians on national health policy, professional standards, and social protection advocacy",
      "Opposes models that commodify healthcare without building social protection floors, citing post-collapse fee-for-service failures",
      "Has resisted parallel NGO health systems that, in his view, undermine public institutions and accelerate physician migration",
    ],
    engagement_recommendation:
      "Engage LMA in the project's clinical governance board as a legitimacy anchor; offer to integrate continuing medical education credits into project training programmes to align with physician professional interests.",
    contact: "https://www.lma.org.lb",
    coordinates: [35.50, 33.91],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Dr. Jad Mahfouz",
    organization: "American University of Beirut Medical Center (AUBMC)",
    current_officeholder: "Dr. Jad Mahfouz",
    type: "academic",
    category: "Academic & Research",
    influence_score: 8,
    stance: "neutral",
    key_positions: [
      "Leads health systems research with WHO co-authorship, focusing on Lebanon's physician emigration crisis and hospital financing",
      "Cautions against project designs that fragment the referral pyramid, citing evidence from post-2006 reconstruction missteps",
      "Advises international donors on evidence-based programme design and has significant influence over how funding is perceived by the medical community",
    ],
    engagement_recommendation:
      "Retain as an independent technical advisor with a mandate to publish peer-reviewed outcome data; this simultaneously builds project credibility and addresses the academic community's scepticism about externally-driven health interventions.",
    contact: "https://www.aub.edu.lb/fm",
    coordinates: [35.48, 33.90],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Global Health Institute â€” American University of Beirut",
    organization: "AUB Global Health Institute",
    current_officeholder: "To be verified",
    type: "academic",
    category: "Academic & Research",
    influence_score: 6,
    stance: "supportive",
    key_positions: [
      "Conducts health systems research and training programmes with focus on conflict-affected populations",
      "Maintains partnerships with Johns Hopkins, Harvard, and WHO for collaborative research and evidence generation",
      "Publishes influential reports on health financing, workforce migration, and access equity in Lebanon",
    ],
    engagement_recommendation:
      "Commission GHI to conduct baseline and evaluation research for the project to generate peer-reviewed evidence and strengthen the project's academic credibility.",
    contact: "https://www.aub.edu.lb/ghi",
    coordinates: [35.48, 33.90],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Hana Sleiman",
    organization: "ALEF â€” Act for Human Rights",
    current_officeholder: "Hana Sleiman",
    type: "ngo",
    category: "Civil Society & NGOs",
    influence_score: 6,
    stance: "opposed",
    key_positions: [
      "Documents healthcare access barriers for displaced Syrian and Palestinian populations and stateless persons in Lebanon",
      "Critically monitors fee-for-service models imposed under economic reform conditionalities, which she argues exclude the poorest quintile",
      "Tracks mental health service collapse in public hospitals and advocates for emergency psychological support funding",
    ],
    engagement_recommendation:
      "Commission an independent social impact assessment prior to launch and formally invite ALEF to participate in the project's civil society review panel to demonstrate accountability to marginalised groups.",
    contact: "https://alefliban.org",
    coordinates: [35.51, 33.91],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Michel Mawad",
    organization: "Amel Association International",
    current_officeholder: "Michel Mawad",
    type: "ngo",
    category: "Civil Society & NGOs",
    influence_score: 7,
    stance: "supportive",
    key_positions: [
      "Operates 32 primary healthcare centres serving over 400,000 beneficiaries annually across 25 Lebanese districts",
      "Built cross-sectarian trust in underserved communities over 40+ years, making Amel a uniquely credible implementation partner",
      "Coordinates with UNHCR and IOM on refugee and migrant health service integration within Lebanon's primary care system",
    ],
    engagement_recommendation:
      "Partner on service delivery implementation through Amel's clinic network to accelerate community reach and bypass bureaucratic delays; Amel's established trust with beneficiaries is a key project risk mitigant.",
    contact: "https://www.amel.org",
    coordinates: [35.49, 33.88],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Mouvement Social",
    organization: "Mouvement Social",
    current_officeholder: "To be verified",
    type: "ngo",
    category: "Civil Society & NGOs",
    influence_score: 5,
    stance: "supportive",
    key_positions: [
      "Operates community development centres providing psychosocial support and primary health referrals in marginalised areas",
      "Strong presence in Tripoli and the North, areas with acute health infrastructure gaps",
      "Community trust built over decades of non-sectarian social work and youth development",
    ],
    engagement_recommendation:
      "Engage Mouvement Social as a community mobilisation partner in Northern Lebanon to facilitate beneficiary outreach and build local ownership of project activities.",
    contact: "https://www.mouvementsocial.org",
    coordinates: [35.52, 33.88],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Rania Farhat",
    organization: "Hariri Foundation for Sustainable Human Development",
    current_officeholder: "Rania Farhat",
    type: "private",
    category: "Private Sector",
    influence_score: 7,
    stance: "supportive",
    key_positions: [
      "Funds community health worker training across 220 Lebanese municipalities, with established networks in Tripoli and Bekaa",
      "Champions a public-private partnership model for clinic rehabilitation, with a track record of USAID and Gulf development fund co-financing",
      "Has relationships with Saudi and Emirati development funds that could be mobilised for complementary project financing",
    ],
    engagement_recommendation:
      "Explore a co-funding arrangement that leverages the Foundation's existing municipal networks and donor trust relationships; propose joint branding of community health worker outputs.",
    contact: "https://www.hfrsd.org",
    coordinates: [35.50, 33.87],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Benta Pharma Group",
    organization: "Benta Pharma Group",
    current_officeholder: "To be verified",
    type: "private",
    category: "Private Sector",
    influence_score: 5,
    stance: "neutral",
    key_positions: [
      "One of Lebanon's largest pharmaceutical manufacturers with local production capacity for essential medicines",
      "Key partner in any pharmaceutical supply chain strengthening initiative due to local manufacturing capabilities",
      "Has interests in both generic drug production and regulatory reform that could align with project objectives",
    ],
    engagement_recommendation:
      "Engage Benta on pharmaceutical supply chain components to leverage local manufacturing capacity and explore partnerships for essential medicine production.",
    contact: "https://www.bentapharma.com",
    coordinates: [35.47, 33.88],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Lebanese Hospital Syndicate",
    organization: "Syndicate of Private Hospitals in Lebanon",
    current_officeholder: "To be verified",
    type: "private",
    category: "Private Sector",
    influence_score: 6,
    stance: "neutral",
    key_positions: [
      "Represents 135+ private hospitals that deliver the majority of inpatient care in Lebanon",
      "Advocates for hospital reimbursement reform and sustainable financing models post-financial crisis",
      "Key stakeholder in any health system reform affecting hospital accreditation or payment mechanisms",
    ],
    engagement_recommendation:
      "Include the Syndicate in project design consultations on hospital financing and accreditation components to ensure buy-in from the private hospital sector.",
    contact: "https://www.syndicateofhospitals.org.lb",
    coordinates: [35.51, 33.89],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Nada Andraos",
    organization: "An-Nahar â€” Health & Society",
    current_officeholder: "Nada Andraos",
    type: "media",
    category: "Media & Communications",
    influence_score: 5,
    stance: "neutral",
    key_positions: [
      "Covers pharmaceutical shortages and hospital closures with nationwide Arabic-language reach, influencing public trust in health interventions",
      "Has reported extensively on NSSF (National Social Security Fund) reform debates and their impact on out-of-pocket healthcare costs",
      "Monitors and amplifies civil society criticism of donor-driven health projects perceived as bypassing state institutions",
    ],
    engagement_recommendation:
      "Develop a media partnership agreement offering structured access to project milestones and patient impact stories in exchange for factual, evidence-based coverage that counters misinformation.",
    contact: "https://www.annahar.com",
    coordinates: [35.50, 33.90],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Lebanon Healthcare Insight",
    organization: "Lebanon Healthcare Insight (LHI)",
    current_officeholder: "To be verified",
    type: "media",
    category: "Media & Communications",
    influence_score: 4,
    stance: "supportive",
    key_positions: [
      "Specialised health sector trade publication reaching healthcare professionals, policymakers, and industry stakeholders",
      "Covers health system reform debates, hospital management innovations, and pharmaceutical sector developments",
      "Provides a platform for evidence-based health policy advocacy and expert commentary",
    ],
    engagement_recommendation:
      "Partner with LHI for targeted communications to healthcare professionals and use their platform to disseminate project findings to the specialist audience.",
    contact: "https://lhi-lb.com",
    coordinates: [35.48, 33.89],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "MTV Lebanon â€” Health Desk",
    organization: "MTV Lebanon",
    current_officeholder: "To be verified",
    type: "media",
    category: "Media & Communications",
    influence_score: 5,
    stance: "neutral",
    key_positions: [
      "Major television broadcaster with regular health segment coverage reaching a broad Lebanese audience",
      "Has covered hospital crisis, physician emigration, and medicine shortages extensively since 2019",
      "Television coverage shapes public perception of health sector interventions more broadly than print media",
    ],
    engagement_recommendation:
      "Offer exclusive broadcast access to project milestones and patient stories to build positive public awareness through Lebanon's most-watched evening news broadcasts.",
    contact: "https://www.mtv.com.lb",
    coordinates: [35.53, 33.90],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
];

const MANAGEMENT_CONSULTING_GCC: Stakeholder[] = [
  {
    name: "Governor, Public Investment Fund (PIF)",
    organization: "Public Investment Fund (PIF) â€” Kingdom of Saudi Arabia",
    current_officeholder: "Yasir Al-Rumayyan",
    type: "government",
    category: "Government & Regulatory",
    influence_score: 10,
    stance: "supportive",
    key_positions: [
      "Directs a $700B+ sovereign wealth fund with the largest consulting vendor spend in the GCC, encompassing strategy, transformation, and programme management mandates",
      "Champions Vision 2030 giga-project delivery that inherently requires global management expertise and creates continuous consulting demand",
      "Has consolidated strategic consulting procurement under PIF's Programme Management Office, requiring approved vendor panel registration",
    ],
    engagement_recommendation:
      "Secure an introductory meeting through mutual investment banking relationships; position the firm as a Vision 2030 delivery partner rather than an advisory vendor, and lead with giga-project operational track record.",
    contact: "https://www.pif.gov.sa",
    coordinates: [46.68, 24.71],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "President, Saudi Industrial Development Fund (SIDF)",
    organization: "Saudi Industrial Development Fund (SIDF)",
    current_officeholder: "To be verified",
    type: "government",
    category: "Government & Regulatory",
    influence_score: 7,
    stance: "neutral",
    key_positions: [
      "Drives localisation (Saudisation) requirements that directly affect consulting firm staffing models and in-Kingdom delivery ratios",
      "Monitors compliance with Vision 2030 human capital development targets and has authority to restrict non-compliant vendors from public sector mandates",
      "Increasingly requires formal knowledge transfer and national talent development commitments as contract conditions for foreign advisory firms",
    ],
    engagement_recommendation:
      "Develop a comprehensive Saudi national talent development plan â€” including graduate hiring targets, secondment programmes, and a Knowledge Transfer Annex â€” as a standard component of every proposal submitted for public sector work.",
    contact: "https://www.sidf.gov.sa",
    coordinates: [46.69, 24.72],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Director General, Sharjah Investment and Development Authority (Shurooq)",
    organization: "Sharjah Investment and Development Authority (Shurooq)",
    current_officeholder: "To be verified",
    type: "government",
    category: "Government & Regulatory",
    influence_score: 7,
    stance: "supportive",
    key_positions: [
      "Champions knowledge economy, creative industries, and cultural tourism as high-growth consulting markets in the UAE's Northern Emirates",
      "Active in WEF, G20 and international policy forums, creating visibility opportunities for firms with aligned thought leadership",
      "Advocates publicly for women's leadership in GCC business transformation, creating reputational alignment opportunities for firms with visible female leadership",
    ],
    engagement_recommendation:
      "Align the firm's ESG and diversity credentials with Shurooq's mandate; propose a joint thought leadership publication on knowledge economy strategy to establish regional presence and access Shurooq's investor network.",
    contact: "https://www.shurooq.gov.ae",
    coordinates: [55.39, 25.34],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Chief Executive, Saudi Tourism Authority (STA)",
    organization: "Saudi Tourism Authority (STA)",
    current_officeholder: "Fahd Hamidaddin",
    type: "government",
    category: "Government & Regulatory",
    influence_score: 8,
    stance: "supportive",
    key_positions: [
      "Oversees an $800B+ tourism giga-project pipeline â€” including NEOM, Red Sea, Diriyah, and Qiddiya â€” creating sustained demand for strategy, operations design, and change management expertise",
      "Operating under aggressive Vision 2030 delivery timelines that create continuous demand for high-capacity consulting teams with rapid mobilisation capability",
      "Preferences firms with demonstrated hospitality sector benchmarking and international tourism master-planning capabilities",
    ],
    engagement_recommendation:
      "Lead with case studies adjacent to NEOM-scale destination development; propose a rapid-mobilisation team structure with a named senior partner dedicated to STA account leadership to demonstrate delivery seriousness.",
    contact: "https://www.sta.gov.sa",
    coordinates: [46.67, 24.70],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Bahrain Economic Development Board (EDB)",
    organization: "Bahrain Economic Development Board",
    current_officeholder: "To be verified",
    type: "government",
    category: "Government & Regulatory",
    influence_score: 6,
    stance: "supportive",
    key_positions: [
      "Positions Bahrain as a regional hub for financial services and professional services firms, offering streamlined licensing",
      "Actively recruits consulting firms to establish regional headquarters in Bahrain as an alternative to Dubai and Riyadh",
      "Provides co-investment incentives and talent subsidies for firms establishing permanent GCC operations",
    ],
    engagement_recommendation:
      "Explore EDB incentives for regional HQ establishment as a complement to Saudi and UAE presence; Bahrain can serve as a lower-cost operational base for Gulf-wide delivery.",
    contact: "https://www.bahrainedb.com",
    coordinates: [50.58, 26.23],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Khaldoon Al Mubarak",
    organization: "Mubadala Investment Company â€” Abu Dhabi",
    current_officeholder: "Khaldoon Al Mubarak",
    type: "private",
    category: "Private Sector",
    influence_score: 9,
    stance: "supportive",
    key_positions: [
      "Oversees an AED 1T+ investment portfolio requiring ongoing organisational transformation, post-merger integration, and operating model redesign support",
      "Prefers long-term embedded advisory partnerships over transactional project mandates, with multi-year framework agreements as the standard engagement model",
      "Selects consulting partners through personal CEO-level referral networks rather than open RFP processes for sensitive transformation mandates",
    ],
    engagement_recommendation:
      "Position the firm as a strategic partner with demonstrated specialisation in energy transition and sovereign wealth fund transformation; engage through Abu Dhabi Global Market (ADGM) relationship channels and request a CEO-level introductory meeting.",
    contact: "https://www.mubadala.com",
    coordinates: [54.37, 24.45],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Fatima Al-Jaber",
    organization: "Al Jaber Group â€” United Arab Emirates",
    current_officeholder: "Fatima Al-Jaber",
    type: "private",
    category: "Private Sector",
    influence_score: 7,
    stance: "neutral",
    key_positions: [
      "Leads a diversified family conglomerate undergoing second-generation governance professionalisation, creating demand for board advisory and family office restructuring expertise",
      "Sceptical of consulting value extraction without substantive knowledge transfer, citing past experiences with deliverable-heavy but impact-light engagements",
      "Influential in Abu Dhabi business council networks, with referral authority across multiple family office and conglomerate relationships",
    ],
    engagement_recommendation:
      "Propose a fixed-fee diagnostic with transparent methodology documentation and a formal knowledge transfer plan; position the firm's local team depth as evidence that Abu Dhabi presence is substantive, not just a regional sales office.",
    contact: "https://www.aljaber.com",
    coordinates: [54.38, 24.46],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Saudi Chambers of Commerce",
    organization: "Federation of Saudi Chambers",
    current_officeholder: "To be verified",
    type: "private",
    category: "Private Sector",
    influence_score: 6,
    stance: "neutral",
    key_positions: [
      "Represents private sector interests across all Saudi regions with direct access to government economic policy discussions",
      "Increasingly vocal about requiring consulting firms to demonstrate measurable ROI and Saudi talent development outcomes",
      "Hosts industry forums and networking events that shape client perceptions of advisory firm credibility",
    ],
    engagement_recommendation:
      "Participate actively in Chamber events and sponsor industry research to build visibility among Saudi private sector decision-makers and demonstrate market commitment.",
    contact: "https://www.csc.org.sa",
    coordinates: [46.70, 24.69],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Oman Investment Authority (OIA)",
    organization: "Oman Investment Authority",
    current_officeholder: "To be verified",
    type: "private",
    category: "Private Sector",
    influence_score: 6,
    stance: "supportive",
    key_positions: [
      "Consolidated sovereign wealth fund driving Oman Vision 2040 economic diversification with growing consulting demand",
      "Smaller budget than PIF/Mubadala but more accessible engagement pathways for mid-tier consulting firms",
      "Actively seeking advisory support for tourism, logistics, and renewable energy sector development",
    ],
    engagement_recommendation:
      "Position as a strategic entry point to the Omani market with tailored sector expertise in Vision 2040 priority areas; leverage lower competition versus Saudi and UAE markets.",
    contact: "https://www.oia.gov.om",
    coordinates: [58.54, 23.59],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Dr. Nasser Saidi",
    organization: "Nasser Saidi & Associates",
    current_officeholder: "Dr. Nasser Saidi",
    type: "academic",
    category: "Academic & Research",
    influence_score: 6,
    stance: "neutral",
    key_positions: [
      "Publishes widely-cited analysis on GCC economic diversification, corporate governance reform, and financial sector development",
      "Advises regional central banks and sovereign funds on structural reform, with access to C-suite and ministerial audiences across the GCC",
      "Frequently quoted in regional and international financial press as an independent voice, shaping business leader perceptions of advisory quality",
    ],
    engagement_recommendation:
      "Engage as a senior regional advisor with a named role in the firm's GCC leadership structure; leverage his media relationships to amplify the firm's thought leadership and provide warm introductions to sovereign fund clients.",
    contact: "https://nassersaidi.com",
    coordinates: [55.27, 25.20],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "INSEAD Abu Dhabi Campus",
    organization: "INSEAD â€” Abu Dhabi",
    current_officeholder: "To be verified",
    type: "academic",
    category: "Academic & Research",
    influence_score: 5,
    stance: "supportive",
    key_positions: [
      "Premier business school in the region producing executive MBA graduates who become consulting clients and recruits",
      "Hosts executive education programmes that build consulting firm brand awareness among GCC C-suite leaders",
      "Research faculty publish on GCC business transformation, family business governance, and sovereign fund strategy",
    ],
    engagement_recommendation:
      "Sponsor executive education modules and recruit from INSEAD Abu Dhabi to build both brand awareness and local talent pipeline simultaneously.",
    contact: "https://www.insead.edu/campuses/abu-dhabi",
    coordinates: [54.39, 24.44],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "King Abdullah University of Science and Technology (KAUST)",
    organization: "KAUST â€” Economic Development",
    current_officeholder: "To be verified",
    type: "academic",
    category: "Academic & Research",
    influence_score: 5,
    stance: "supportive",
    key_positions: [
      "Research university with strong technology transfer and innovation ecosystem development programmes",
      "Hosts startup accelerators and innovation challenges that create advisory opportunities in technology commercialisation",
      "Connected to Saudi government's innovation agenda with direct links to ministry-level decision-makers",
    ],
    engagement_recommendation:
      "Partner with KAUST on innovation ecosystem advisory work to demonstrate technology sector expertise and build relationships with Saudi innovation policymakers.",
    contact: "https://www.kaust.edu.sa",
    coordinates: [46.71, 24.73],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Eiman Al-Mutawa",
    organization: "Arabian Business â€” Strategy & Markets Editor",
    current_officeholder: "Eiman Al-Mutawa",
    type: "media",
    category: "Media & Communications",
    influence_score: 5,
    stance: "neutral",
    key_positions: [
      "Covers GCC corporate transformation, C-suite strategy, and consulting firm market dynamics with pan-Gulf digital and print readership",
      "Tracks consulting firm project wins, partner movements, and regional market share â€” directly influencing client perception of firm standing",
      "Influential in shaping regional business leaders' perceptions of which advisory firms are considered credible regional players versus global firms parachuting in",
    ],
    engagement_recommendation:
      "Offer exclusive data from an original GCC consulting market study or regional benchmark report in exchange for branded feature coverage of the firm's regional practice; establish a standing quarterly briefing relationship.",
    contact: "https://www.arabianbusiness.com",
    coordinates: [55.27, 25.20],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Zawya (Refinitiv) â€” GCC Markets",
    organization: "Zawya / Refinitiv â€” MENA",
    current_officeholder: "To be verified",
    type: "media",
    category: "Media & Communications",
    influence_score: 4,
    stance: "neutral",
    key_positions: [
      "Financial data and news platform widely used by GCC institutional investors, sovereign funds, and corporate strategists",
      "Project announcements and deal coverage on Zawya directly influence RFP invitation lists and vendor perceptions",
      "Tracks GCC project pipeline and M&A activity that consulting firms use for business development intelligence",
    ],
    engagement_recommendation:
      "Ensure the firm's project wins and thought leadership are distributed through Zawya's news service to reach institutional decision-makers who use the platform for vendor discovery.",
    contact: "https://www.zawya.com",
    coordinates: [55.28, 25.21],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Gulf News â€” Business Section",
    organization: "Gulf News",
    current_officeholder: "To be verified",
    type: "media",
    category: "Media & Communications",
    influence_score: 5,
    stance: "neutral",
    key_positions: [
      "Largest English-language daily in the UAE with significant readership among business executives and government officials",
      "Regular coverage of consulting industry trends, major project awards, and economic transformation initiatives",
      "Opinion pages provide platform for thought leadership positioning among GCC business audiences",
    ],
    engagement_recommendation:
      "Develop an op-ed series on GCC economic transformation themes for Gulf News to build thought leadership visibility among UAE-based decision-makers.",
    contact: "https://gulfnews.com",
    coordinates: [55.26, 25.19],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "GCC Chambers of Commerce Union",
    organization: "Federation of GCC Chambers of Commerce & Industry",
    current_officeholder: "To be verified",
    type: "ngo",
    category: "Civil Society & NGOs",
    influence_score: 5,
    stance: "neutral",
    key_positions: [
      "Pan-GCC business advocacy body that shapes regional trade policy and professional services market access",
      "Hosts GCC-wide business forums and trade delegations that create networking opportunities with decision-makers",
      "Advocates for harmonised professional services regulation across GCC member states",
    ],
    engagement_recommendation:
      "Engage with the Federation to understand evolving GCC-wide professional services regulations and participate in pan-Gulf trade forums for cross-border visibility.",
    contact: "https://www.fgccc.org",
    coordinates: [50.10, 26.43],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Pearl Initiative",
    organization: "Pearl Initiative â€” Gulf Region",
    current_officeholder: "To be verified",
    type: "ngo",
    category: "Civil Society & NGOs",
    influence_score: 4,
    stance: "supportive",
    key_positions: [
      "UN-supported corporate governance and transparency advocacy organisation working across the Gulf region",
      "Promotes anti-corruption best practices and ESG standards that align with consulting firm governance advisory services",
      "Convenes GCC business leaders on corporate accountability themes, creating client engagement opportunities",
    ],
    engagement_recommendation:
      "Partner with Pearl Initiative on corporate governance research and events to build the firm's ESG credentials and access their network of GCC business leaders.",
    contact: "https://www.pearlinitiative.org",
    coordinates: [55.40, 25.35],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "Tamkeen â€” Bahrain Labour Fund",
    organization: "Tamkeen",
    current_officeholder: "To be verified",
    type: "ngo",
    category: "Civil Society & NGOs",
    influence_score: 5,
    stance: "supportive",
    key_positions: [
      "Bahrain's national labour market development agency funding enterprise development and workforce training",
      "Provides co-financing for consulting engagements focused on Bahraini business capacity building",
      "Drives localisation targets that create demand for consulting services with knowledge transfer components",
    ],
    engagement_recommendation:
      "Explore Tamkeen co-financing for consulting engagements with Bahraini firms to reduce client cost barriers and demonstrate commitment to Gulf national workforce development.",
    contact: "https://www.tamkeen.bh",
    coordinates: [50.58, 26.23],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "IFC â€” GCC Advisory Services",
    organization: "International Finance Corporation â€” GCC",
    current_officeholder: "To be verified",
    type: "international",
    category: "International Organizations & Donors",
    influence_score: 6,
    stance: "supportive",
    key_positions: [
      "Provides advisory services and investment to GCC entities on privatisation, PPP structuring, and institutional reform",
      "Partners with consulting firms on large-scale reform mandates, creating co-advisory and subcontracting opportunities",
      "Has credibility with GCC governments as a neutral reform partner, providing access to mandates sensitive to perceived conflicts of interest",
    ],
    engagement_recommendation:
      "Register on IFC's approved vendor panel and build relationships with the GCC advisory team to access reform mandates that require neutral third-party advisory support.",
    contact: "https://www.ifc.org/en/where-we-work/middle-east-and-north-africa",
    coordinates: [54.36, 24.47],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "OECD â€” MENA Economic Governance Programme",
    organization: "OECD â€” MENA Competitiveness Programme",
    current_officeholder: "To be verified",
    type: "international",
    category: "International Organizations & Donors",
    influence_score: 5,
    stance: "neutral",
    key_positions: [
      "Provides economic governance benchmarking and reform advisory to GCC governments seeking OECD alignment",
      "Publishes comparative reports on business environment reforms that shape GCC government advisory procurement priorities",
      "Convenes ministerial-level reform dialogue that creates visibility for firms contributing to OECD programming",
    ],
    engagement_recommendation:
      "Contribute to OECD-MENA working groups and co-author reform benchmarking reports to build institutional credibility and access government reform mandates across the GCC.",
    contact: "https://www.oecd.org/en/topics/sub-issues/middle-east-and-north-africa-mena.html",
    coordinates: [55.30, 25.25],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
  {
    name: "GIZ â€” Gulf Cooperation Programme",
    organization: "Deutsche Gesellschaft fÃ¼r Internationale Zusammenarbeit (GIZ)",
    current_officeholder: "To be verified",
    type: "international",
    category: "International Organizations & Donors",
    influence_score: 4,
    stance: "supportive",
    key_positions: [
      "German development agency with bilateral programmes in Saudi Arabia and UAE focused on economic diversification and sustainability",
      "Partners with consulting firms for technical advisory on energy transition, labour market reform, and institutional capacity building",
      "Provides access to government counterparts through trusted bilateral cooperation frameworks",
    ],
    engagement_recommendation:
      "Explore GIZ partnership opportunities for technical advisory mandates that leverage German bilateral relationships with GCC governments, particularly in energy transition and institutional reform.",
    contact: "https://www.giz.de/en/worldwide/gulf-cooperation.html",
    coordinates: [46.70, 24.73],
    sources: [], source_years: [], generated_date: "2025-04-20",
  },
];

export interface DemoScenario {
  sector: string;
  region: string;
  stakeholders: Stakeholder[];
}

const DEMO_SCENARIOS: DemoScenario[] = [
  {
    sector: "Renewable Energy",
    region: "Lebanon",
    stakeholders: RENEWABLE_ENERGY_LEBANON,
  },
  {
    sector: "Public Health",
    region: "Lebanon",
    stakeholders: PUBLIC_HEALTH_LEBANON,
  },
  {
    sector: "Management Consulting",
    region: "GCC",
    stakeholders: MANAGEMENT_CONSULTING_GCC,
  },
];

/** Returns demo stakeholders if the query matches a preset, otherwise null. */
export function getDemoData(sector: string, region: string): DemoScenario | null {
  const s = sector.toLowerCase().trim();
  const r = region.toLowerCase().trim();

  for (const scenario of DEMO_SCENARIOS) {
    const matchSector = s.includes(scenario.sector.toLowerCase());
    const matchRegion = r.includes(scenario.region.toLowerCase()) ||
      scenario.region.toLowerCase().includes(r);
    if (matchSector && matchRegion) return scenario;
  }
  return null;
}

export const DEMO_HINTS = DEMO_SCENARIOS.map(
  (s) => `${s.sector} (${s.region})`
).join(", ");


